
require 'osaka/scriptrunner'
require 'osaka/location'
require 'osaka/remotecontrol'
require 'osaka/typicalapplication'
require 'osaka/typicalfinderdialog'
require 'osaka/typicalopendialog'
require 'osaka/typicalsavedialog'
require 'osaka/typicalprintdialog'
require 'osaka/pages'
require 'osaka/numbers'
require 'osaka/keynote'
require 'osaka/calculator'
require 'osaka/textedit'
require 'osaka/mailmergeflow'
require 'osaka/keynoteflow'
require 'osaka/osakaexpectations'

